# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='employee_code',
        ),
    ]
