# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_profile_employee_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(default='', max_length=60)),
                ('Last_Name', models.CharField(default='', max_length=60)),
                ('Date_of_Birth', models.DateField()),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=100)),
                ('Island', models.CharField(blank=True, choices=[('Santo', 'Santo'), ('Ambae', 'Ambae'), ('Pentecost', 'Pentecost'), ('Maewo', 'Maewo'), ('Malekula', 'Malekula'), ('Ambrym', 'Ambrym'), ('Paama', 'Paama'), ('Epi', 'Epi'), ('Efate', 'Efate'), ('Tana', 'Tana')], default='', max_length=100)),
                ('Date_of_Baptism', models.DateField()),
                ('Province', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
