# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='Province',
            field=models.CharField(blank=True, choices=[('Torba', 'Torba'), ('Sanma', 'Sanma'), ('Penama', 'Panama'), ('Malampa', 'Malampa'), ('Shefa', 'Shefa'), ('Tafea', 'Tafea')], default='', max_length=100),
        ),
    ]
