# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20180512_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='Date_of_Baptism',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Date_of_Birth',
            field=models.DateField(null=True),
        ),
    ]
