# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20180512_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadfolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_to_upload', models.FileField(upload_to='var/www/vmachies/registery/media')),
            ],
        ),
    ]
