# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20180515_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfolder',
            name='File_to_upload',
            field=models.FileField(upload_to='var/www/vmachines/registry/media'),
        ),
    ]
