# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20180515_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfolder',
            name='File_to_upload',
            field=models.FileField(upload_to=''),
        ),
    ]
