# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20180515_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='Date_of_Birth',
            field=models.DateField(),
        ),
    ]
