# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20180525_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Taken_By', models.CharField(max_length=100)),
                ('Agender', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
