# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='Island',
            field=models.CharField(blank=True, choices=[('Torres', 'Torres'), ('Banks', 'Banks'), ('Santo', 'Santo'), ('Ambae', 'Ambae'), ('Pentecost', 'Pentecost'), ('Maewo', 'Maewo'), ('Malekula', 'Malekula'), ('Ambrym', 'Ambrym'), ('Paama', 'Paama'), ('Epi', 'Epi'), ('Tongoa', 'Tongoa'), ('Tongariki', 'Tongariki'), ('Emae', 'Emae'), ('Makira', 'Makira'), ('Mataso', 'Mataso'), ('Efate', 'Efate'), ('Erromango', 'Erromango'), ('Tana', 'Tana'), ('Aniwa', 'Aniwa'), ('Futuna', 'Futuna')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Province',
            field=models.CharField(blank=True, choices=[('Torba', 'Torba'), ('Sanma', 'Sanma'), ('Penama', 'Penama'), ('Malampa', 'Malampa'), ('Shefa', 'Shefa'), ('Tafea', 'Tafea')], default='', max_length=100),
        ),
    ]
