# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20180629_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='Date_of_Birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Middle_Name',
            field=models.CharField(default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
